### ISSUE TITLE
bug: Error: connect() timed out after 5000 ms 

### ISSUE THREAD

**Issue by bweston92** [ledhed2222/nftdemo#22]
```
errors.ts:16 Uncaught (in promise) NotConnectedError: Error: connect() timed out after 5000 ms. If your internet connection is working, the rippled server may be blocked or inaccessible. You can also try setting the 'connectionTimeout' option in the RippleAPI constructor.
    at Connection._onConnectionFailed (connection.ts:452:1)
    at connection.ts:488:1
```

I can see the connection in the network tab. I can also see that when I've scanned the QR code there is an opened event. I just keep getting the error above there after, if I press the X I can see the create form but button is disabled because client isn't connected.

Any ideas?

**Comment by bweston92** [comment]
Ok it actually seems like it cannot connect to `wss://uhm.solike.wtf:7007/`. I'm trying to figure out what this address is but cannot find anything.

**Comment by bweston92** [comment]
Would this be the address of an XRP node?

**Comment by ledhed2222** [comment]
it connects to the nft sandbox now :)
